### ISSUE TITLE
System.Data.DataException: Error parsing column 0 (Name=<null>) ---> System.Reflection.TargetException: Non-static method requires a target

### ISSUE THREAD

**Issue by anandjaisy** [jmg48/NSubstitute.DbConnection#8]
Using asp.net core 7 with NSubstitte, xunit, and Dapper, I have the below code as below

Dapper code working with real connection

```
public async Task UpdateStatus(AuthorityStatusUpdateInputDto input)
        {
            using var connection = _dapperContextBuilder.CreateConnection();
            var query = _dapperContextBuilder.QueryBuilder(
                new {TemplateId = id, TenantId = AbpSession.TenantId, TemplateType = EditionTemplateType.Authority},
                "SELECT TOP 1 * FROM MarketplaceItem");
            Marketplace.MarketplaceItem marketplaceItem =
                await connection.QueryFirstOrDefaultAsync<Marketplace.MarketplaceItem>(query.Item1, query.Item2);

            if (marketplaceItem != null)
                await _marketplaceItemRepository.DeleteAsync(marketplaceItem);
        }
```

Test

 ```
private readonly IDbConnection _fakedbConnection;
     public AppService_Tests()
            {
                _fakedbConnection = Substitute.For<IDbConnection>().SetupCommands();
            }
    
             [Fact]
            public async Task Should_UpdateStatus_As_Edit()
            {
                // Arrange
                
                string delete_query = "SELECT TOP 1 * FROM MarketplaceItem WHERE TemplateId = @TemplateId AND TenantId = @TenantId AND TemplateType = @TemplateType AND IsDeleted = 0";
                var connectionFactory = Substitute.For<IDapperContextBuilder>();
                 connectionFactory.CreateConnection().Returns(_fakedbConnection);
                UsingDbContext(async context =>
                {
                    var marketplaceItem = context.MarketplaceItem.FirstOrDefault(); --> This values is NULL
                    _fakedbConnection.SetupQuery(delete_query).Returns(marketplaceItem);
                });
    
                var dto = new AuthorityStatusUpdateInputDto()
                {
                    Id = id,
                    Status = AuthorityStatus.Edit
                };
                await _authorityAppService.UpdateStatus(dto);
    
                //Asserts
            }

```

Since the value is return NULL for `var marketplaceItem = context.MarketplaceItem.FirstOrDefault(); ` for the connection `_fakedbConnection.SetupQuery(delete_query).Returns(marketplaceItem);` however the exception is thrown as below and it is only for Unit Test for the WEB API it is working fine. This issue is that I have the null value in the marketplaceItem variable, and sometime the value will be null because there is a check

```
if (marketplaceItem != null)
                await _marketplaceItemRepository.DeleteAsync(marketplaceItem);
enter image description here
```

Exception

    ```
System.Data.DataException: Error parsing column 0 (Name=<null>)
 ---> System.Reflection.TargetException: Non-static method requires a target.
   at System.Reflection.MethodBase.ValidateInvokeTarget(Object target)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at NSubstitute.DbConnection.MockQuery.<>c__DisplayClass29_0.<ExecuteReader>b__7(CallInfo ci)
   at NSubstitute.Core.ReturnValueFromFunc`1.ReturnFor(CallInfo info)
   at NSubstitute.Core.CallResults.ResultForCallSpec.GetResult(ICall call, ICallInfoFactory callInfoFactory)
   at NSubstitute.Core.CallResults.TryGetResult(ICall call, Object& result)
   at NSubstitute.Routing.Handlers.ReturnConfiguredResultHandler.Handle(ICall call)
   at NSubstitute.Routing.Route.Handle(ICall call)
   at NSubstitute.Core.CallRouter.Route(ICall call)
   at NSubstitute.Proxies.CastleDynamicProxy.CastleForwardingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at NSubstitute.Proxies.CastleDynamicProxy.ProxyIdInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.DbDataReaderProxy.get_Item(Int32 ordinal)
   at Deserializeb55939c3-2c31-4e08-bd4b-606d843266ec(DbDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3878
   at Deserializeb55939c3-2c31-4e08-bd4b-606d843266ec(DbDataReader)
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command)
   at LegalRegTech.MasterData.AuthorityAppService.DeleteAuthorityFromMarketplace(Int32 id)
[c#](https://stackoverflow.com/questions/tagged/c%23)[asp.net](https://stackoverflow.com/questions/tagged/asp.net)[asp.net-core](https://stackoverflow.com/questions/tagged/asp.net-core)[xunit](https://stackoverflow.com/questions/tagged/xunit)[dapper](https://stackoverflow.com/questions/tagged/dapper)[Edit tags](javascript:void(0))
```

**Comment by jmg48** [comment]
Thanks for getting in touch - I'll take a look and try and repro this in the next few days

Jon

**Comment by jmg48** [comment]
So, I think in the case that `FirstOrDefault()` returns null, that actually means that the result set of the query is an empty array, rather than null. So try setting up the mock to return `new [] { }` instead of null

**Comment by anandjaisy** [comment]
> So, I think in the case that `FirstOrDefault()` returns null, that actually means that the result set of the query is an empty array, rather than null. So try setting up the mock to return `new [] { }` instead of null

@jmg48 I get the compile error with that 

` _fakedbConnection.SetupQuery(delete_query).Returns(new [] {});`

`No best type found for implicitly-typed array`

If I do with object `_fakedbConnection.SetupQuery(delete_query).Returns(new [] {new Marketplace.MarketplaceItem()});` I get the error because the property is null

```
System.Data.DataException: Error parsing column 9 (TemplateType=<null>)
 ---> System.InvalidOperationException: Nullable object must have a value.
```

**Comment by jmg48** [comment]
Yes, sorry I was using `new [] { }` to indicate that you need an empty array here, but the implicitly-typed declaration won't actually work because the type isn't already implied. Your replacement is an array of one element rather than an empty array, which I don't think is the correct response for your mocked query. You could use `new Marketplace.MarketplaceItem[] { }` or `new Marketplace.MarketplaceItem[0]` or even `new List<Marketplace.MarketplaceItem>()` to explicitly specify the type of an empty array / collection

**Comment by anandjaisy** [comment]
@jmg48  How do I solve, if the Object of a certain property of NULLABLE type has value null

One of the property `public CreatedFromMethod? CreatedFromMethod { get; set; }
`
```
System.Data.DataException: Error parsing column 67 (CreatedFromMethod=<null>)
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at System.Nullable`1.op_Explicit(Nullable`1 value)
   at Deserialize29dcf897-a5e3-41dd-9744-1578b9997c59(DbDataReader)
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3878
   at Deserialize29dcf897-a5e3-41dd-9744-1578b9997c59(DbDataReader)
   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command)
   at LegalRegTech.Assessments.AssessmentHistoryAppService.GetAssessmentHistory(GetAssessmentHistoryDto getAssessmentHistoryDto, CancellationToken cancellationToken)
```

Also how to test the below as well

```
var assessmentChangeMetadataQueryResult  = await connection.QueryAsync<ChangeMetadata, HistoricalChangeDto, User,ChangeMetadata>(assessmentChangeMetadataQuery,
                (changeMetadata,historicalChange,user) =>
                {
                    changeMetadata.User = user;
                    changeMetadata.Change = historicalChange;
                    return changeMetadata;
                },
                splitOn: "Id,Id");
```


```
System.ArgumentException: Multi-map error: splitOn column 'Id' was not found - please ensure your splitOn parameter is set and in the correct order (Parameter 'splitOn')
   at Dapper.SqlMapper.GetNextSplit(Int32 startIdx, String splitOn, DbDataReader reader) in /_/Dapper/SqlMapper.cs:line 1788
   at Dapper.SqlMapper.GenerateDeserializers(Identity identity, String splitOn, DbDataReader reader) in /_/Dapper/SqlMapper.cs:line 1733
   at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, DbDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1546
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.MultiMapAsync[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn) in /_/Dapper/SqlMapper.Async.cs:line 91
```
